# Generated by Django 3.1.2 on 2020-10-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('population', models.PositiveIntegerField(verbose_name='population')),
                ('area', models.FloatField(verbose_name='area (sq. meter)')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('population', models.PositiveIntegerField(verbose_name='population')),
                ('area', models.FloatField(verbose_name='area (sq. meter)')),
            ],
            options={
                'verbose_name': 'continent',
                'verbose_name_plural': 'continents',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('population', models.PositiveIntegerField(verbose_name='population')),
                ('area', models.FloatField(verbose_name='area (sq. meter)')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.continent', verbose_name='continent')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CountryStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hospitals', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of hospitals')),
                ('number_of_national_parks', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of national parks')),
                ('number_of_rivers', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of rivers')),
                ('number_of_schools', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of schools')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'country stats',
                'verbose_name_plural': 'countries stats',
            },
        ),
        migrations.CreateModel(
            name='CityStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_roads', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of roads')),
                ('number_of_trees', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of trees')),
                ('number_of_shops', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of shops')),
                ('number_of_schools', models.PositiveIntegerField(blank=True, null=True, verbose_name='number of schools')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.city', verbose_name='city')),
            ],
            options={
                'verbose_name': 'city stats',
                'verbose_name_plural': 'cities stats',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.country', verbose_name='country'),
        ),
    ]
